import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import './globals.css'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Explorer from "@/components/Explorer";
import {Providers} from "@/redux/Provider";
import Tabs from "@/components/Tabs";
import SideBar from "@/components/SideBar";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className="font-sans">
    <Providers>
      <Navbar/>
      <Explorer/>
      <main className={`${montserrat.className} w-full pl-[300px] pb-[26px] max-md:pl-[230px] max-md:pb-0 max-sm:pl-0`}>
        <Tabs/>
        <div>
          <SideBar />
          {children}
        </div>
      </main>
      <Footer/>
    </Providers>
    </body>
    </html>
  )
}
