import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Explorer from "@/components/Explorer";
import {Providers} from "@/redux/Provider";
import Tabs from "@/components/Tabs";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar/>
          <Explorer/>
          <main>
            <Tabs/>
            {children}
          </main>
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
